/**
 * Timeago is a jQuery plugin that makes it easy to support automatically
 * updating fuzzy timestamps (e.g. "4 minutes ago" or "about 1 day ago").
 *
 * @name timeago
 * @version 1.3.0
 * @requires jQuery v1.2.3+
 * @author Ryan McGeary
 * @license MIT License - http://www.opensource.org/licenses/mit-license.php
 *
 * For usage and examples, visit:
 * http://timeago.yarp.com/
 *
 * Copyright (c) 2008-2013, Ryan McGeary (ryan -[at]- mcgeary [*dot*] org)
 */
(function(n){typeof define=="function"&&define.amd?define(["jquery"],n):n(jQuery)})(function(n){function u(){var r=e(this),u=t.settings;return isNaN(r.datetime)||(u.cutoff==0||f(r.datetime)<u.cutoff)&&n(this).text(i(r.datetime)),this}function e(i){if(i=n(i),!i.data("timeago")){i.data("timeago",{datetime:t.datetime(i)});var r=n.trim(i.text());t.settings.localeTitle?i.attr("title",i.data("timeago").datetime.toLocaleString()):r.length>0&&!(t.isTime(i)&&i.attr("title"))&&i.attr("title",r)}return i.data("timeago")}function i(n){return t.inWords(f(n))}function f(n){return(new Date).getTime()-n.getTime()}var t,r;n.timeago=function(t){return t instanceof Date?i(t):typeof t=="string"?i(n.timeago.parse(t)):typeof t=="number"?i(new Date(t)):i(n.timeago.datetime(t))},t=n.timeago,n.extend(n.timeago,{settings:{refreshMillis:6e4,allowFuture:!1,localeTitle:!1,cutoff:0,strings:{prefixAgo:null,prefixFromNow:null,suffixAgo:"ago",suffixFromNow:"from now",seconds:"less than a minute",minute:"about a minute",minutes:"%d minutes",hour:"about an hour",hours:"about %d hours",day:"a day",days:"%d days",month:"about a month",months:"%d months",year:"about a year",years:"%d years",wordSeparator:" ",numbers:[]}},inWords:function(t){function r(r,u){var f=n.isFunction(r)?r(u,t):r,e=i.numbers&&i.numbers[u]||u;return f.replace(/%d/i,e)}var i=this.settings.strings,h=i.prefixAgo,c=i.suffixAgo,a,s;this.settings.allowFuture&&t<0&&(h=i.prefixFromNow,c=i.suffixFromNow);var f=Math.abs(t)/1e3,e=f/60,o=e/60,u=o/24,l=u/365;return a=f<45&&r(i.seconds,Math.round(f))||f<90&&r(i.minute,1)||e<45&&r(i.minutes,Math.round(e))||e<90&&r(i.hour,1)||o<24&&r(i.hours,Math.round(o))||o<42&&r(i.day,1)||u<30&&r(i.days,Math.round(u))||u<45&&r(i.month,1)||u<365&&r(i.months,Math.round(u/30))||l<1.5&&r(i.year,1)||r(i.years,Math.round(l)),s=i.wordSeparator||"",i.wordSeparator===undefined&&(s=" "),n.trim([h,a,c].join(s))},parse:function(t){var i=n.trim(t);return i=i.replace(/\.\d+/,""),i=i.replace(/-/,"/").replace(/-/,"/"),i=i.replace(/T/," ").replace(/Z/," UTC"),i=i.replace(/([\+\-]\d\d)\:?(\d\d)/," $1$2"),new Date(i)},datetime:function(i){var r=t.isTime(i)?n(i).attr("datetime"):n(i).attr("title");return t.parse(r)},isTime:function(t){return n(t).get(0).tagName.toLowerCase()==="time"}}),r={init:function(){var r=n.proxy(u,this),i;r(),i=t.settings,i.refreshMillis>0&&setInterval(r,i.refreshMillis)},update:function(i){n(this).data("timeago",{datetime:t.parse(i)}),u.apply(this)},updateFromDOM:function(){n(this).data("timeago",{datetime:t.parse(t.isTime(this)?n(this).attr("datetime"):n(this).attr("title"))}),u.apply(this)}},n.fn.timeago=function(n,t){var i=n?r[n]:r.init;if(!i)throw new Error("Unknown function name '"+n+"' for timeago");return this.each(function(){i.call(this,t)}),this},document.createElement("abbr"),document.createElement("time")});